# Generated by Django 2.0.2 on 2018-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtasks', '0002_task_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='feedback',
        ),
    ]
