# Generated by Django 2.0.2 on 2018-04-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtasks', '0004_auto_20180418_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='resolution',
            new_name='feedback',
        ),
    ]
