# Generated by Django 2.0.2 on 2018-04-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtasks', '0007_auto_20180419_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, max_length=2000, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='task',
            name='resolution',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='resolution'),
        ),
    ]
